((nil . ((mocha-which-node . "/Users/ajs/.nvm/versions/node/v4.2.2/bin/node")
         (mocha-command . "node_modules/.bin/mocha")
         (mocha-environment-variables . "NODE_ENV=test")
         (mocha-options . "--recursive --reporter dot -t 5000")
         (mocha-project-test-directory . "test")
         (mocha-reporter . "spec"))))
