((nil . ((mocha-which-node . "node")
         (mocha-command . "./node_modules/.bin/mocha")
         (mocha-environment-variables . "NODE_ENV=test")
         (mocha-options . "--compilers js:babel-core/register -w --recursive --reporter dot -t 5000")
         (mocha-project-test-directory . "t")
         (mocha-reporter . "spec"))))
